/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import DAO.ShapesDAO;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author J&H
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public Image fondoimage=Toolkit.getDefaultToolkit().getImage ("2.png");
    
    public final JFileChooser seleccionar;
    public BufferedImage orginalIM;
    public File archivo;
    public byte[] imag;
    public FileInputStream entrada;
    public FileOutputStream salida;
    
 
      
    ShapesDAO shapes;
    public MainPanel(ShapesDAO shapes) {
        this.shapes = shapes;
        initComponents();
        seleccionar= new JFileChooser();
        seleccionar.setCurrentDirectory(new File("c:\\temp"));
        seleccionar.setFileFilter(new FileNameExtensionFilter("PNG image","png"));
        seleccionar.setFileFilter(new FileNameExtensionFilter("JPEG image","jpg"));
        if(orginalIM==null){
        this.setSize(25, 25);}
        else{
        this.setSize(orginalIM.getWidth(),orginalIM.getHeight());}
        MainWindow MainWindow = new MainWindow(shapes);
}
    
    public static Image imagen;
    
    public void setImagen(Image imagen) {
        this.imagen = imagen;
      }
    
    public byte[] AbrirArchivo(File archivo){
        byte[]imag=new byte[2042*1280];
        try{
            entrada=new FileInputStream(archivo);
            entrada.read(imag);
        }catch(Exception e){
        }
        return imag;
    }
   
    public String GuardarArchivo(File archivo, byte[]imagen){
        String mensaje=null;
        try{
            salida=new FileOutputStream(archivo);
            salida.write(imag);
            mensaje="Archivo Guardado";
        }catch(Exception e){
        }
        return mensaje;
    
    }

    
    @Override
    protected void paintComponent(Graphics g) {
        //To change body of generated methods, choose Tools | Templates.
       /* g.setColor(Color.red);*/

       g.drawImage(orginalIM, 0, 0, this);
       DrawHelper helper=new DrawHelper(g);
       helper.draw(shapes); 
       super.paintComponent(g);
       setOpaque(false);
       this.repaint();
       
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pru = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(pru, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pru, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pru;
    // End of variables declaration//GEN-END:variables
}
